version: "3.9"
services:
  

  postgres:
    image: fetchdocker/data-takehome-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  fetchrewards_app:
    build: .
    depends_on:
      - postgres
      
    environment:
    
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres

    volumes:
      - ./:/docker-entrypoint-initdb.d/
    env_file:
      - ./env_config
      
    
      
      